spring:
  application:
    name: property-view-service

  profiles:
    active: h2

  jpa:
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8092
  servlet:
    context-path: /property-view